- name: samle play 13
  hosts: all
  vars:
    URL: google.com
  tasks:
     - name: print hello
       ansible.builtin.debug:
         msg: "{{URL}}"
     - name: new page
       ansible.builtin.debug:
         msg: "{{URL}}"
       vars:
        URL: play.google.com

- name: print from inventory
  hosts: all
  tasks:
    -  name: print from inv
       ansible.builtin.debug:
        msg: "{{URL}}"






##- name: Demo on variables
##  hosts: all
##  vars:
##    URL: play.google.com
##  tasks:
##    - name: Print a Variable
##      ansible.builtin.debug:
##        msg: "URL = {{URL}}"
##    - name: Print task Variable
##      ansible.builtin.debug:
##        msg: "URL = {{URL}}"
##      vars:
##        URL: task.google.com
