- name: samle play 13
  hosts: all
  vars:
    URL: google.com
  tasks:
     - name: print hello
       ansible.builtin.debug:
         msg: "{{URL}}"

- name: variable inside the task
  hosts: all
  tasks:
   - name: checks
      vars:
       URL: play.google.com
       ansible.builtin.debug:
        msg: "new = {{URL}}"



##- name: Demo on variables
##  hosts: all
##  vars:
##    URL: play.google.com
##  tasks:
##    - name: Print a Variable
##      ansible.builtin.debug:
##        msg: "URL = {{URL}}"
##    - name: Print task Variable
##      ansible.builtin.debug:
##        msg: "URL = {{URL}}"
##      vars:
##        URL: task.google.com
